---
- hosts: servers
  become: true
  tasks:
    - name: Copy node_exporter binary
      copy:
        src: /home/casper/installer/node_exporter
        dest: /home/ubuntu/node_exporter
        mode: 0755
      become: true

    - name: Copy install script
      copy:
        src: /home/casper/installer/install_enable_node_ex.sh
        dest: /home/ubuntu/install_enable_node_ex.sh
        mode: 0755
      become: true

    - name: Check file permissions
      file:
        path: /home/ubuntu/install_enable_node_ex.sh
        mode: 0755

    - name: Run install script
      command: bash /home/ubuntu/install_enable_node_ex.sh
      become: true
    
    - name: Run install script
      command: echo '* libraries/restart-without-asking boolean true' | sudo debconf-set-selections
      become: true
    
    - name:
      command: apt update
      become: true
    
    - name:
      command: apt install stress
      become: true

    - name: Reload systemd
      systemd:
        name: daemon-reload
        state: reload

    - name: Start node_exporter service
      systemd:
        name: node_exporter.service
        state: started
        enabled: yes

